<?php

namespace ContainerZy5JHUX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_YVZav3MService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.YVZav3M' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.YVZav3M'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'expenseRepository' => ['privates', 'App\\Repository\\ExpenseRepository', 'getExpenseRepositoryService', true],
        ], [
            'expenseRepository' => 'App\\Repository\\ExpenseRepository',
        ]);
    }
}
