<?php

namespace ContainerZy5JHUX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AEvIRJ6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aEvIRJ6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aEvIRJ6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ExpenseController::all' => ['privates', '.service_locator.YVZav3M', 'get_ServiceLocator_YVZav3MService', true],
            'App\\Controller\\ExpenseController::index' => ['privates', '.service_locator.YVZav3M', 'get_ServiceLocator_YVZav3MService', true],
            'App\\Controller\\ExpenseController::new' => ['privates', '.service_locator.YVZav3M', 'get_ServiceLocator_YVZav3MService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Controller\\ExpenseController:all' => ['privates', '.service_locator.YVZav3M', 'get_ServiceLocator_YVZav3MService', true],
            'App\\Controller\\ExpenseController:index' => ['privates', '.service_locator.YVZav3M', 'get_ServiceLocator_YVZav3MService', true],
            'App\\Controller\\ExpenseController:new' => ['privates', '.service_locator.YVZav3M', 'get_ServiceLocator_YVZav3MService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
        ], [
            'App\\Controller\\ExpenseController::all' => '?',
            'App\\Controller\\ExpenseController::index' => '?',
            'App\\Controller\\ExpenseController::new' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\ExpenseController:all' => '?',
            'App\\Controller\\ExpenseController:index' => '?',
            'App\\Controller\\ExpenseController:new' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
