<?php

namespace ContainerZy5JHUX;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExpenseTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\ExpenseType' shared autowired service.
     *
     * @return \App\Form\ExpenseType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/ExpenseType.php';

        return $container->privates['App\\Form\\ExpenseType'] = new \App\Form\ExpenseType();
    }
}
