<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZy5JHUX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZy5JHUX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZy5JHUX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZy5JHUX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZy5JHUX\App_KernelDevDebugContainer([
    'container.build_hash' => 'Zy5JHUX',
    'container.build_id' => '0cd8dd36',
    'container.build_time' => 1705532091,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZy5JHUX');
