<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
    'app_expense_index' => [[], ['_controller' => 'App\\Controller\\ExpenseController::index'], [], [['text', '/expense/']], [], [], []],
    'app_expense_new' => [[], ['_controller' => 'App\\Controller\\ExpenseController::new'], [], [['text', '/expense/new']], [], [], []],
    'app_expense_all' => [[], ['_controller' => 'App\\Controller\\ExpenseController::all'], [], [['text', '/expense/all']], [], [], []],
    'app_index' => [[], ['_controller' => 'App\\Controller\\ExpenseController::index'], [], [['text', '/']], [], [], []],
];
